using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LF_Zestaw4_z2.DicePokerGame
{
    public enum Rank
    {
        Nothing,
        PairOne,
        PairTwo,
        PairThree,
        PairFour,
        PairFive,
        PairSix,
        DoublePairTwoOne,
        DoublePairThreeOne,
        DoublePairThreeTwo,
        DoublePairFourOne,
        DoublePairFourTwo,
        DoublePairFiveOne,
        DoublePairFourThree,
        DoublePairFiveTwo,
        DoublePairSixOne,
        DoublePairFiveThree,
        DoublePairSixTwo,
        DoublePairFiveFour,
        DoublePairSixThree,
        DoublePairSixFour,
        DoublePairSixFive,
        TripleOne,
        TripleTwo,
        TripleThree,
        TripleFour,
        TripleFive,
        TripleSix,
        FiveHighStraight,
        SixHighStraight,
        TripleOnePairTwo,
        TripleOnePairThree,
        TripleOnePairFour,
        TripleOnePairFive,
        TripleOnePairSix,
        TripleTwoPairOne,
        TripleTwoPairThree,
        TripleTwoPairFour,
        TripleTwoPairFive,
        TripleTwoPairSix,
        TripleThreePairOne,
        TripleThreePairTwo,
        TripleThreePairFour,
        TripleThreePairFive,
        TripleThreePairSix,
        TripleFourPairOne,
        TripleFourPairTwo,
        TripleFourPairThree,
        TripleFourPairFive,
        TripleFourPairSix,
        TripleFivePairOne,
        TripleFivePairTwo,
        TripleFivePairThree,
        TripleFivePairFour,
        TripleFivePairSix,
        TripleSixPairOne,
        TripleSixPairTwo,
        TripleSixPairThree,
        TripleSixPairFour,
        TripleSixPairFive,
        QuadrupleOne,
        QuadrupleTwo,
        QuadrupleThree,
        QuadrupleFour,
        QuadrupleFive,
        QuadrupleSix,
        QuintupleOne,
        QuintupleTwo,
        QuintupleThree,
        QuintupleFour,
        QuintupleFive,
        QuintupleSix
    }
}
